// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"io"
	"sync"
)

// InjectorMock is a mock implementation of turn.Injector.
//
//	func TestSomethingThatUsesInjector(t *testing.T) {
//
//		// make and configure a mocked turn.Injector
//		mockedInjector := &InjectorMock{
//			TypeFunc: func(contextMoqParam context.Context, writer io.Writer, s string) error {
//				panic("mock out the Type method")
//			},
//		}
//
//		// use mockedInjector in code that requires turn.Injector
//		// and then make assertions.
//
//	}
type InjectorMock struct {
	// TypeFunc mocks the Type method.
	TypeFunc func(contextMoqParam context.Context, writer io.Writer, s string) error

	// calls tracks calls to the methods.
	calls struct {
		// Type holds details about calls to the Type method.
		Type []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Writer is the writer argument value.
			Writer io.Writer
			// S is the s argument value.
			S string
		}
	}
	lockType sync.RWMutex
}

// Type calls TypeFunc.
func (mock *InjectorMock) Type(contextMoqParam context.Context, writer io.Writer, s string) error {
	if mock.TypeFunc == nil {
		panic("InjectorMock.TypeFunc: method is nil but Injector.Type was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Writer          io.Writer
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		Writer:          writer,
		S:               s,
	}
	mock.lockType.Lock()
	mock.calls.Type = append(mock.calls.Type, callInfo)
	mock.lockType.Unlock()
	return mock.TypeFunc(contextMoqParam, writer, s)
}

// TypeCalls gets all the calls that were made to Type.
// Check the length with:
//
//	len(mockedInjector.TypeCalls())
func (mock *InjectorMock) TypeCalls() []struct {
	ContextMoqParam context.Context
	Writer          io.Writer
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		Writer          io.Writer
		S               string
	}
	mock.lockType.RLock()
	calls = mock.calls.Type
	mock.lockType.RUnlock()
	return calls
}
