// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/fya/app/stream"
)

// OutputMock is a mock implementation of turn.Output.
//
//	func TestSomethingThatUsesOutput(t *testing.T) {
//
//		// make and configure a mocked turn.Output
//		mockedOutput := &OutputMock{
//			EventFunc: func(event stream.Event) error {
//				panic("mock out the Event method")
//			},
//			FinalFunc: func(result stream.Result) error {
//				panic("mock out the Final method")
//			},
//			TextFunc: func(s string) error {
//				panic("mock out the Text method")
//			},
//		}
//
//		// use mockedOutput in code that requires turn.Output
//		// and then make assertions.
//
//	}
type OutputMock struct {
	// EventFunc mocks the Event method.
	EventFunc func(event stream.Event) error

	// FinalFunc mocks the Final method.
	FinalFunc func(result stream.Result) error

	// TextFunc mocks the Text method.
	TextFunc func(s string) error

	// calls tracks calls to the methods.
	calls struct {
		// Event holds details about calls to the Event method.
		Event []struct {
			// Event is the event argument value.
			Event stream.Event
		}
		// Final holds details about calls to the Final method.
		Final []struct {
			// Result is the result argument value.
			Result stream.Result
		}
		// Text holds details about calls to the Text method.
		Text []struct {
			// S is the s argument value.
			S string
		}
	}
	lockEvent sync.RWMutex
	lockFinal sync.RWMutex
	lockText  sync.RWMutex
}

// Event calls EventFunc.
func (mock *OutputMock) Event(event stream.Event) error {
	if mock.EventFunc == nil {
		panic("OutputMock.EventFunc: method is nil but Output.Event was just called")
	}
	callInfo := struct {
		Event stream.Event
	}{
		Event: event,
	}
	mock.lockEvent.Lock()
	mock.calls.Event = append(mock.calls.Event, callInfo)
	mock.lockEvent.Unlock()
	return mock.EventFunc(event)
}

// EventCalls gets all the calls that were made to Event.
// Check the length with:
//
//	len(mockedOutput.EventCalls())
func (mock *OutputMock) EventCalls() []struct {
	Event stream.Event
} {
	var calls []struct {
		Event stream.Event
	}
	mock.lockEvent.RLock()
	calls = mock.calls.Event
	mock.lockEvent.RUnlock()
	return calls
}

// Final calls FinalFunc.
func (mock *OutputMock) Final(result stream.Result) error {
	if mock.FinalFunc == nil {
		panic("OutputMock.FinalFunc: method is nil but Output.Final was just called")
	}
	callInfo := struct {
		Result stream.Result
	}{
		Result: result,
	}
	mock.lockFinal.Lock()
	mock.calls.Final = append(mock.calls.Final, callInfo)
	mock.lockFinal.Unlock()
	return mock.FinalFunc(result)
}

// FinalCalls gets all the calls that were made to Final.
// Check the length with:
//
//	len(mockedOutput.FinalCalls())
func (mock *OutputMock) FinalCalls() []struct {
	Result stream.Result
} {
	var calls []struct {
		Result stream.Result
	}
	mock.lockFinal.RLock()
	calls = mock.calls.Final
	mock.lockFinal.RUnlock()
	return calls
}

// Text calls TextFunc.
func (mock *OutputMock) Text(s string) error {
	if mock.TextFunc == nil {
		panic("OutputMock.TextFunc: method is nil but Output.Text was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockText.Lock()
	mock.calls.Text = append(mock.calls.Text, callInfo)
	mock.lockText.Unlock()
	return mock.TextFunc(s)
}

// TextCalls gets all the calls that were made to Text.
// Check the length with:
//
//	len(mockedOutput.TextCalls())
func (mock *OutputMock) TextCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockText.RLock()
	calls = mock.calls.Text
	mock.lockText.RUnlock()
	return calls
}
