// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/fya/app/ptyrun"
	"github.com/umputun/fya/app/turn"
)

// ProcessStarterMock is a mock implementation of turn.ProcessStarter.
//
//	func TestSomethingThatUsesProcessStarter(t *testing.T) {
//
//		// make and configure a mocked turn.ProcessStarter
//		mockedProcessStarter := &ProcessStarterMock{
//			StartFunc: func(contextMoqParam context.Context, config ptyrun.Config) (turn.Session, error) {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedProcessStarter in code that requires turn.ProcessStarter
//		// and then make assertions.
//
//	}
type ProcessStarterMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(contextMoqParam context.Context, config ptyrun.Config) (turn.Session, error)

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Config is the config argument value.
			Config ptyrun.Config
		}
	}
	lockStart sync.RWMutex
}

// Start calls StartFunc.
func (mock *ProcessStarterMock) Start(contextMoqParam context.Context, config ptyrun.Config) (turn.Session, error) {
	if mock.StartFunc == nil {
		panic("ProcessStarterMock.StartFunc: method is nil but ProcessStarter.Start was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Config          ptyrun.Config
	}{
		ContextMoqParam: contextMoqParam,
		Config:          config,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(contextMoqParam, config)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedProcessStarter.StartCalls())
func (mock *ProcessStarterMock) StartCalls() []struct {
	ContextMoqParam context.Context
	Config          ptyrun.Config
} {
	var calls []struct {
		ContextMoqParam context.Context
		Config          ptyrun.Config
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
