// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// SessionMock is a mock implementation of turn.Session.
//
//	func TestSomethingThatUsesSession(t *testing.T) {
//
//		// make and configure a mocked turn.Session
//		mockedSession := &SessionMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			DoneFunc: func() <-chan struct{} {
//				panic("mock out the Done method")
//			},
//			OutputFunc: func() string {
//				panic("mock out the Output method")
//			},
//			WaitFunc: func() error {
//				panic("mock out the Wait method")
//			},
//			WriteStringFunc: func(s string) error {
//				panic("mock out the WriteString method")
//			},
//		}
//
//		// use mockedSession in code that requires turn.Session
//		// and then make assertions.
//
//	}
type SessionMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// DoneFunc mocks the Done method.
	DoneFunc func() <-chan struct{}

	// OutputFunc mocks the Output method.
	OutputFunc func() string

	// WaitFunc mocks the Wait method.
	WaitFunc func() error

	// WriteStringFunc mocks the WriteString method.
	WriteStringFunc func(s string) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Done holds details about calls to the Done method.
		Done []struct {
		}
		// Output holds details about calls to the Output method.
		Output []struct {
		}
		// Wait holds details about calls to the Wait method.
		Wait []struct {
		}
		// WriteString holds details about calls to the WriteString method.
		WriteString []struct {
			// S is the s argument value.
			S string
		}
	}
	lockClose       sync.RWMutex
	lockDone        sync.RWMutex
	lockOutput      sync.RWMutex
	lockWait        sync.RWMutex
	lockWriteString sync.RWMutex
}

// Close calls CloseFunc.
func (mock *SessionMock) Close() error {
	if mock.CloseFunc == nil {
		panic("SessionMock.CloseFunc: method is nil but Session.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedSession.CloseCalls())
func (mock *SessionMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Done calls DoneFunc.
func (mock *SessionMock) Done() <-chan struct{} {
	if mock.DoneFunc == nil {
		panic("SessionMock.DoneFunc: method is nil but Session.Done was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDone.Lock()
	mock.calls.Done = append(mock.calls.Done, callInfo)
	mock.lockDone.Unlock()
	return mock.DoneFunc()
}

// DoneCalls gets all the calls that were made to Done.
// Check the length with:
//
//	len(mockedSession.DoneCalls())
func (mock *SessionMock) DoneCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDone.RLock()
	calls = mock.calls.Done
	mock.lockDone.RUnlock()
	return calls
}

// Output calls OutputFunc.
func (mock *SessionMock) Output() string {
	if mock.OutputFunc == nil {
		panic("SessionMock.OutputFunc: method is nil but Session.Output was just called")
	}
	callInfo := struct {
	}{}
	mock.lockOutput.Lock()
	mock.calls.Output = append(mock.calls.Output, callInfo)
	mock.lockOutput.Unlock()
	return mock.OutputFunc()
}

// OutputCalls gets all the calls that were made to Output.
// Check the length with:
//
//	len(mockedSession.OutputCalls())
func (mock *SessionMock) OutputCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockOutput.RLock()
	calls = mock.calls.Output
	mock.lockOutput.RUnlock()
	return calls
}

// Wait calls WaitFunc.
func (mock *SessionMock) Wait() error {
	if mock.WaitFunc == nil {
		panic("SessionMock.WaitFunc: method is nil but Session.Wait was just called")
	}
	callInfo := struct {
	}{}
	mock.lockWait.Lock()
	mock.calls.Wait = append(mock.calls.Wait, callInfo)
	mock.lockWait.Unlock()
	return mock.WaitFunc()
}

// WaitCalls gets all the calls that were made to Wait.
// Check the length with:
//
//	len(mockedSession.WaitCalls())
func (mock *SessionMock) WaitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockWait.RLock()
	calls = mock.calls.Wait
	mock.lockWait.RUnlock()
	return calls
}

// WriteString calls WriteStringFunc.
func (mock *SessionMock) WriteString(s string) error {
	if mock.WriteStringFunc == nil {
		panic("SessionMock.WriteStringFunc: method is nil but Session.WriteString was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockWriteString.Lock()
	mock.calls.WriteString = append(mock.calls.WriteString, callInfo)
	mock.lockWriteString.Unlock()
	return mock.WriteStringFunc(s)
}

// WriteStringCalls gets all the calls that were made to WriteString.
// Check the length with:
//
//	len(mockedSession.WriteStringCalls())
func (mock *SessionMock) WriteStringCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockWriteString.RLock()
	calls = mock.calls.WriteString
	mock.lockWriteString.RUnlock()
	return calls
}
