// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/fya/app/transcript"
)

// TailerMock is a mock implementation of turn.Tailer.
//
//	func TestSomethingThatUsesTailer(t *testing.T) {
//
//		// make and configure a mocked turn.Tailer
//		mockedTailer := &TailerMock{
//			ReadNewFunc: func() ([]transcript.Event, error) {
//				panic("mock out the ReadNew method")
//			},
//		}
//
//		// use mockedTailer in code that requires turn.Tailer
//		// and then make assertions.
//
//	}
type TailerMock struct {
	// ReadNewFunc mocks the ReadNew method.
	ReadNewFunc func() ([]transcript.Event, error)

	// calls tracks calls to the methods.
	calls struct {
		// ReadNew holds details about calls to the ReadNew method.
		ReadNew []struct {
		}
	}
	lockReadNew sync.RWMutex
}

// ReadNew calls ReadNewFunc.
func (mock *TailerMock) ReadNew() ([]transcript.Event, error) {
	if mock.ReadNewFunc == nil {
		panic("TailerMock.ReadNewFunc: method is nil but Tailer.ReadNew was just called")
	}
	callInfo := struct {
	}{}
	mock.lockReadNew.Lock()
	mock.calls.ReadNew = append(mock.calls.ReadNew, callInfo)
	mock.lockReadNew.Unlock()
	return mock.ReadNewFunc()
}

// ReadNewCalls gets all the calls that were made to ReadNew.
// Check the length with:
//
//	len(mockedTailer.ReadNewCalls())
func (mock *TailerMock) ReadNewCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReadNew.RLock()
	calls = mock.calls.ReadNew
	mock.lockReadNew.RUnlock()
	return calls
}
