// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// SourceMock is a mock implementation of ready.Source.
//
//	func TestSomethingThatUsesSource(t *testing.T) {
//
//		// make and configure a mocked ready.Source
//		mockedSource := &SourceMock{
//			DoneFunc: func() <-chan struct{} {
//				panic("mock out the Done method")
//			},
//			OutputFunc: func() string {
//				panic("mock out the Output method")
//			},
//		}
//
//		// use mockedSource in code that requires ready.Source
//		// and then make assertions.
//
//	}
type SourceMock struct {
	// DoneFunc mocks the Done method.
	DoneFunc func() <-chan struct{}

	// OutputFunc mocks the Output method.
	OutputFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Done holds details about calls to the Done method.
		Done []struct {
		}
		// Output holds details about calls to the Output method.
		Output []struct {
		}
	}
	lockDone   sync.RWMutex
	lockOutput sync.RWMutex
}

// Done calls DoneFunc.
func (mock *SourceMock) Done() <-chan struct{} {
	if mock.DoneFunc == nil {
		panic("SourceMock.DoneFunc: method is nil but Source.Done was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDone.Lock()
	mock.calls.Done = append(mock.calls.Done, callInfo)
	mock.lockDone.Unlock()
	return mock.DoneFunc()
}

// DoneCalls gets all the calls that were made to Done.
// Check the length with:
//
//	len(mockedSource.DoneCalls())
func (mock *SourceMock) DoneCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDone.RLock()
	calls = mock.calls.Done
	mock.lockDone.RUnlock()
	return calls
}

// Output calls OutputFunc.
func (mock *SourceMock) Output() string {
	if mock.OutputFunc == nil {
		panic("SourceMock.OutputFunc: method is nil but Source.Output was just called")
	}
	callInfo := struct {
	}{}
	mock.lockOutput.Lock()
	mock.calls.Output = append(mock.calls.Output, callInfo)
	mock.lockOutput.Unlock()
	return mock.OutputFunc()
}

// OutputCalls gets all the calls that were made to Output.
// Check the length with:
//
//	len(mockedSource.OutputCalls())
func (mock *SourceMock) OutputCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockOutput.RLock()
	calls = mock.calls.Output
	mock.lockOutput.RUnlock()
	return calls
}
